# Generated by Django 2.2 on 2019-04-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Кандидат',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Планета',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='PadawanTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='код ордена')),
                ('padawan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Candidate')),
            ],
            options={
                'verbose_name': 'Тестовое испытание падавана',
            },
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Planet', verbose_name='планета, на которой он обучает')),
            ],
            options={
                'verbose_name': 'Джедай',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Planet', verbose_name='планета обитания'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(verbose_name='ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.PadawanTest')),
            ],
            options={
                'verbose_name': 'Ответ',
            },
        ),
    ]
