# Generated by Django 2.2 on 2019-04-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jediAcademy', '0002_auto_20190403_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
    ]
