# Generated by Django 2.2 on 2019-04-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jediAcademy', '0003_auto_20190403_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.PadawanTest', verbose_name='тестовое испытание'),
        ),
        migrations.AlterField(
            model_name='padawantest',
            name='padawan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Candidate', verbose_name='кандидат в падаваны'),
        ),
    ]
