# Generated by Django 2.2 on 2019-04-06 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jediAcademy', '0004_auto_20190403_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Jedi', verbose_name='учитель'),
            preserve_default=False,
        ),
    ]
