# Generated by Django 2.2 on 2019-04-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jediAcademy', '0005_candidate_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jediAcademy.Jedi', verbose_name='учитель'),
        ),
    ]
