# Generated by Django 2.2 on 2019-04-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jediAcademy', '0006_auto_20190407_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawantest',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='код ордена'),
        ),
    ]
